version: '3.8'

services:
  zonos-api:
    build: .
    image: jiufen/zonos-api:latest
    container_name: zonos-api
    ports:
      - "8000:8000"
    volumes:
      - ./generated:/app/generated
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
